Add integration test for ErrTraceNotFound
jaegertracing/jaeger pull request #2478
Opened 2020-09-15 04:05 UTC by yurishkuro

This is especially interesting when using go-plugin based storage, where the error has to be correctly passed through gRPC client.

2020-09-15 07:27 UTC, objectiser approved these changes
LGTM - although the title is a bit misleading, as the integration test was already testing for `ErrTraceNotFound`, so assume it wasn't being run against badger?

2020-09-15 08:45 UTC, jpkrohling commented
This is related to #2471, isn't it?

2020-09-15 12:43 UTC, jpkrohling requested changes
I'm blocking this for now, because of the test failure. Looks like the same is being addressed in another PR already, so, we might want to close this.

2020-09-15 15:20 UTC, yurishkuro commented
> although the title is a bit misleading, as the integration test was already testing for ErrTraceNotFound, so assume it wasn't being run against badger

@objectiser where do you see integration test checking for NotFound?  Badger implementation clearly did not satisfy the API contract for that (which I also fix in this PR), yet it was passing integration tests, so I assume there was no explicit test for NotFound.

@jpkrohling I don't know if #2471 is fixing the same issue (and it's doing it incorrectly anyway, findTraces _can_ return empty list).

2020-09-15 15:30 UTC, objectiser commented
@yurishkuro yep, lgtm.

2020-09-15 15:33 UTC, yurishkuro commented
I added documentation to the span Reader API with expectations about not-found.

2020-09-16 09:01 UTC, jpkrohling approved these changes

2020-09-16 09:01 UTC, jpkrohling commented
Thanks for documenting the interface!

2020-09-16 09:02 UTC, merged