Wait for elasticsearch/opensearch to be ready before running the integration tests
jaegertracing/jaeger pull request #3416
Opened 2021-11-29 13:39 UTC by Ashmita152

Signed-off-by: Ashmita Bohara <ashmita.bohara@logz.io>

## Which problem is this PR solving?
- Resolves https://github.com/jaegertracing/jaeger/issues/3411

## Short description of the changes
- We are waiting for elasticsearch/opensearch to be ready before running the integration tests
- Bumping opensearch container version to 1.2.0.

2021-11-29 13:59 UTC, pavolloffay approved these changes

2021-11-29 13:59 UTC, yurishkuro commented on scripts/es-integration-test.sh
> +}
I would recommend failing the whole script if 200 was never achieved, this way we'd get a much earlier and clearer failure signal.

2021-11-29 14:01 UTC, yurishkuro commented on scripts/es-integration-test.sh
> +}
i.e. something like this:
```
while counter < 30 {
    status = $(curl)
    if status == 200 then return 0
}
return 1
```

2022-01-20 13:04 UTC, yurishkuro requested changes
per comments

2022-03-07 04:31 UTC, Ashmita152 commented
Hi Yuri, sorry for the huge delay on my side.

2022-03-07 05:58 UTC, yurishkuro approved these changes
👏 👏 👏

2022-03-07 06:23 UTC, merged