code fixes to use new grpc api
jaegertracing/jaeger pull request #5335
Opened 2024-04-06 20:16 UTC by danish9039

## Which problem is this PR solving?
- fix #5327

## Description of the changes
- fixes code for using new grpc api

## How was this change tested?
- make test 
- make lint

## Checklist
- [ ] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [ ] I have signed all commits
- [ ] I have added unit tests for the new functionality
- [ ] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `yarn lint` and `yarn test`

2024-04-06 20:43 UTC, yurishkuro commented on cmd/agent/app/processors/thrift_processor_test.go
> +	grpc.NewClient(grpcCollector.Listener().Addr().String(), grpc.WithTransportCredentials(insecure.NewCredentials()))
Twice?

2024-04-06 20:43 UTC, yurishkuro commented on proto-gen/api_v2/sampling.pb.go
> +		return nil, fmt.Errorf("Error while dialing: %w",err)
This is autogenerated file, please revert

2024-04-06 23:46 UTC, yurishkuro requested changes

2024-04-06 23:46 UTC, yurishkuro commented on plugin/storage/grpc/factory_test.go
> -	require.ErrorContains(t, err, "grpc-plugin builder failed to create a store: error connecting to remote storage")
Not equivalent change

2024-04-21 16:04 UTC, Pushkarm029 commented on cmd/agent/app/configmanager/grpc/manager.go
> +		return nil, fmt.Errorf("our internal message/explanation: %w", err)
```suggestion
		return nil, fmt.Errorf("failed to get sampling strategies: %w", err)
```
this can be improved

2024-04-26 23:11 UTC, yurishkuro commented
fixed in https://github.com/jaegertracing/jaeger/pull/5336

2024-04-26 23:11 UTC, closed without merging