[jaeger-v2] Add Meter Provider To Telemetry Settings
jaegertracing/jaeger pull request #6132
Opened 2024-10-27 20:23 UTC by Garvit-77

## Which problem is this PR solving?
- Resolves #6127 

## Description of the changes
- Added the Meter Provider to telemetry Settings.go 

## Checklist
- [ ] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [ ] I have signed all commits
- [ ] I have added unit tests for the new functionality
- [ ] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `yarn lint` and `yarn test`

2024-10-27 20:28 UTC, Garvit-77 commented
@mahadzaryab1 The metric.NewMeterProvider has an Option input 
(https://pkg.go.dev/go.opentelemetry.io/otel/sdk/metric#NewMeterProvider)

2024-10-27 20:49 UTC, yurishkuro requested changes
there's no value in this change unless this provider is wired in and used where appropriate

2024-10-28 18:39 UTC, Garvit-77 commented
> there's no value in this change unless this provider is wired in and used where appropriate

the MeterProvider msut be initialized with Which option Reader, Resources or Views
@yurishkuro

2024-10-28 18:49 UTC, yurishkuro commented
we don't need to initialize it, in jaeger-v2 it is already provided. When used in v1 context we can use noop

2025-01-02 22:53 UTC, yurishkuro commented
already addressed

2025-01-02 22:53 UTC, closed without merging